name: gast_cinema
description: Gast Project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flip_card: ^0.6.0
  flutter_native_splash: ^2.2.16
  provider: ^6.0.5
  sizer: ^2.0.15
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0
  change_app_package_name: ^1.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  build_runner: ^2.3.3
  flutter_vector_icons: ^2.0.0
  image_picker: ^0.8.7+5
  image_cropper: ^3.0.3
  #phosphor_flutter: ^2.0.0
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.1
  flutter_shake_animated: ^0.0.5
  #parse_server_sdk_flutter: ^4.0.0
  loading_animation_widget: ^1.2.0+4
  pocketbase: ^0.10.3
  #parse_server_sdk: ^5.1.2
  ticket_widget: ^0.0.1
  timelines: ^0.1.0
  modal_bottom_sheet: ^2.1.2
  flutter_swipe_button: ^2.1.1+1
  shimmer: ^3.0.0
  flutter_settings_ui: ^2.0.1
  random_avatar: ^0.0.8
  firebase_app_check: ^0.1.1+5
  firebase_crashlytics: ^3.0.6
  firebase_core: ^2.1.1
  firebase_auth: ^4.2.6
  firebase_messaging: ^14.0.3
  pin_code_fields: ^7.2.0
  http: ^0.13.6
  # chapasdk: ^0.0.6
  go_router: ^10.1.2
  flutter_inappwebview: ^5.7.2+3
  chapasdk:
    path: ./chapa-flutter/chapa-flutter
  uuid: ^4.0.0
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  injectable: ^2.3.0
  get_it: ^7.6.4
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/cinema/
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#ffffff"
  image: assets/tr_logo_200.png
  color_dark: "#26282C"
  image_dark: assets/tr_logo_200.png

  android_12:
    image: assets/tr_logo_200.png
    icon_background_color: "#ffffff"
    image_dark: assets/tr_logo_200.png
    icon_background_color_dark: "#26282C"

  web: false
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
